import type {
  PatternOptions,
  PatternPreset,
  PatternPresetId,
  PatternPresetOptions,
  Symmetry,
} from "./types.js";

const MET_SOURCES = ["SRC-MET-001", "SRC-MET-002", "SRC-MET-003"] as const;
const BOTANICAL_VISUAL_SOURCES = ["SRC-VIS-PIN-BOARD-001", "SRC-MET-003"] as const;

export const PRESETS = {
  "construction-grid": {
    id: "construction-grid",
    label: "Construction grid",
    kind: "grid",
    constructionId: "orthogonal-grid-v2",
    description: "Exact square, triangular, or radial divisions selected by symmetry.",
    sourceIds: ["SRC-MET-003"],
    defaults: { symmetry: 8, density: 0.55, interlace: false },
    validSymmetries: [4, 6, 8, 10, 12, 16],
    topology: {
      mode: "periodic",
      rotationOrder: 4,
      interlace: "none",
      edgeContinuity: "repeat-matched",
      prototiles: ["square", "triangle", "radial-sector"],
    },
  },
  "khatam-8-star-cross": {
    id: "khatam-8-star-cross",
    label: "Eight-fold star and cross",
    kind: "star",
    constructionId: "khatam-8-v2",
    description: "Square-repeat eight-point star, cross, kite, and almond-petal modules.",
    sourceIds: MET_SOURCES,
    defaults: { symmetry: 8, density: 0.68, interlace: true },
    validSymmetries: [8],
    topology: {
      mode: "periodic",
      rotationOrder: 8,
      interlace: "continuous-straps",
      edgeContinuity: "repeat-matched",
      prototiles: ["eight-point-star", "cross", "kite", "almond-petal"],
    },
  },
  "rosette-12-almond": {
    id: "rosette-12-almond",
    label: "Twelve-fold almond rosette",
    kind: "rosette",
    constructionId: "rosette-12-v2",
    description: "Layered twelve-fold rosette with compass-derived almond petals and connectors.",
    sourceIds: MET_SOURCES,
    defaults: { symmetry: 12, density: 0.72, crop: "circle", interlace: false },
    validSymmetries: [12],
    topology: {
      mode: "focal",
      rotationOrder: 12,
      interlace: "none",
      edgeContinuity: "frame-terminated",
      prototiles: ["almond-petal", "connector-kite", "dodecagon"],
    },
  },
  "medallion-16-nested": {
    id: "medallion-16-nested",
    label: "Sixteen-fold nested medallion",
    kind: "star",
    constructionId: "medallion-16-v2",
    description: "A dense bounded sixteen-fold composition with nested stars, petals, kites, and color facets.",
    sourceIds: MET_SOURCES,
    defaults: {
      symmetry: 16,
      density: 0.78,
      crop: "circle",
      interlace: true,
      palette: ["#184f78", "#d56a32", "#f2dfb4", "#2f7566"],
    },
    validSymmetries: [16],
    topology: {
      mode: "focal",
      rotationOrder: 16,
      interlace: "continuous-straps",
      edgeContinuity: "frame-terminated",
      prototiles: ["sixteen-point-star", "almond-petal", "connector-kite"],
    },
  },
  "girih-10-straps": {
    id: "girih-10-straps",
    label: "Ten-fold girih tile patch",
    kind: "girih",
    constructionId: "girih-10-v2",
    description: "A clean periodic ten-fold star network; prototile boundaries remain construction guides.",
    sourceIds: ["SRC-MET-001", "SRC-SCI-001", "SRC-SCI-002", "SRC-SCI-003"],
    defaults: { symmetry: 10, density: 0.62, interlace: true },
    validSymmetries: [10],
    topology: {
      mode: "periodic",
      rotationOrder: 10,
      interlace: "continuous-straps",
      edgeContinuity: "repeat-matched",
      prototiles: ["decagon", "pentagon", "bowtie", "rhombus"],
    },
  },
  "zellige-star-cross": {
    id: "zellige-star-cross",
    label: "Star-and-cross tile repeat",
    kind: "zellige",
    constructionId: "zellige-star-cross-v2",
    description: "An exact square repeat decomposed into eight-point stars and concave crosses.",
    sourceIds: ["SRC-MET-001", "SRC-MET-002", "SRC-VA-PER-002"],
    defaults: {
      symmetry: 8,
      density: 0.7,
      interlace: false,
      palette: ["#1f5a50", "#d58a2c", "#f0dfbd", "#2f79a0"],
    },
    validSymmetries: [8],
    topology: {
      mode: "periodic",
      rotationOrder: 8,
      interlace: "none",
      edgeContinuity: "repeat-matched",
      prototiles: ["eight-point-star", "cross"],
    },
  },
  "jali-8-screen": {
    id: "jali-8-screen",
    label: "Eight-fold screen lattice",
    kind: "screen",
    constructionId: "jali-8-v2",
    description: "A continuous 4.8.8 edge lattice of regular octagons and rotated squares.",
    sourceIds: ["SRC-MET-001", "SRC-MET-002"],
    defaults: { symmetry: 8, density: 0.58, interlace: false },
    validSymmetries: [8],
    topology: {
      mode: "periodic",
      rotationOrder: 8,
      interlace: "continuous-straps",
      edgeContinuity: "repeat-matched",
      prototiles: ["regular-octagon", "square"],
    },
  },
  "pointed-arch": {
    id: "pointed-arch",
    label: "Two-center pointed arch",
    kind: "arch",
    constructionId: "pointed-arch-v2",
    description: "A bounded two-center compass arch with nested construction offsets.",
    sourceIds: ["SRC-MET-003"],
    defaults: { symmetry: 4, density: 0.5, interlace: false },
    validSymmetries: [4],
    topology: {
      mode: "bounded",
      rotationOrder: 4,
      interlace: "none",
      edgeContinuity: "frame-terminated",
      prototiles: ["circular-arc", "spring-line"],
    },
  },
  "khatam-corners": {
    id: "khatam-corners",
    label: "Eight-fold corner fragments",
    kind: "corners",
    constructionId: "khatam-corners-v2",
    description: "Mirrored quarter fragments of the eight-fold star-and-cross construction.",
    sourceIds: MET_SOURCES,
    defaults: { symmetry: 8, density: 0.52, interlace: true },
    validSymmetries: [8],
    topology: {
      mode: "bounded",
      rotationOrder: 8,
      interlace: "continuous-straps",
      edgeContinuity: "frame-terminated",
      prototiles: ["quarter-star", "kite"],
    },
  },
  "geometric-frame": {
    id: "geometric-frame",
    label: "Star-and-cross boundary frame",
    kind: "frame",
    constructionId: "geometric-frame-v2",
    description: "A module-aligned boundary band derived from the eight-fold repeat.",
    sourceIds: MET_SOURCES,
    defaults: { symmetry: 8, density: 0.48, interlace: true },
    validSymmetries: [8],
    topology: {
      mode: "bounded",
      rotationOrder: 8,
      interlace: "continuous-straps",
      edgeContinuity: "frame-terminated",
      prototiles: ["eight-point-star", "cross", "corner-kite"],
    },
  },
  "rumi-medallion-6": {
    id: "rumi-medallion-6",
    label: "Six-fold Rumi medallion",
    kind: "arabesque",
    constructionId: "rumi-medallion-6-v2",
    description:
      "A bounded six-fold whirling medallion of compass petals, split leaves, S-scrolls, and a floral void.",
    sourceIds: BOTANICAL_VISUAL_SOURCES,
    defaults: {
      symmetry: 6,
      density: 0.68,
      crop: "circle",
      interlace: false,
      petalDepth: 0.2,
      botanicalFill: true,
      strandWidth: 2.2,
      weaveGap: 1.6,
    },
    validSymmetries: [6],
    topology: {
      mode: "focal",
      rotationOrder: 6,
      interlace: "none",
      edgeContinuity: "frame-terminated",
      prototiles: [
        "reference-circle",
        "s-curve",
        "split-leaf",
        "almond-petal",
        "six-point-floral-void",
      ],
    },
  },
  "palmette-roundel": {
    id: "palmette-roundel",
    label: "Bilateral palmette roundel",
    kind: "arabesque",
    constructionId: "palmette-roundel-v2",
    description:
      "A bounded bilateral roundel with mirrored palmettes, split leaves, lotus buds, and hooked tendrils.",
    sourceIds: BOTANICAL_VISUAL_SOURCES,
    defaults: {
      symmetry: 2,
      density: 0.64,
      crop: "circle",
      interlace: false,
      petalDepth: 0.2,
      botanicalFill: true,
      strandWidth: 2,
      weaveGap: 1.5,
      palette: ["#173b6c", "#c79a3b", "#f3ead5", "#6e88ad"],
    },
    validSymmetries: [2],
    topology: {
      mode: "focal",
      rotationOrder: 2,
      interlace: "none",
      edgeContinuity: "frame-terminated",
      prototiles: [
        "mirrored-palmette",
        "split-leaf",
        "lotus-bud",
        "s-tendril",
        "circular-boundary",
      ],
    },
  },
  "floral-geometric-field": {
    id: "floral-geometric-field",
    label: "Floral-geometric repeat field",
    kind: "arabesque",
    constructionId: "floral-geometric-field-v2",
    description:
      "An exact eight- or twelve-fold square repeat governing almond leaves, kite connectors, and rosette nodes.",
    sourceIds: BOTANICAL_VISUAL_SOURCES,
    defaults: {
      symmetry: 8,
      density: 0.7,
      interlace: false,
      petalDepth: 0.16,
      botanicalFill: true,
      strandWidth: 1.6,
      weaveGap: 1.2,
    },
    validSymmetries: [8, 12],
    topology: {
      mode: "periodic",
      rotationOrder: 8,
      interlace: "none",
      edgeContinuity: "repeat-matched",
      prototiles: [
        "almond-petal",
        "split-leaf",
        "connector-kite",
        "rosette-node",
        "square-repeat-cell",
      ],
    },
  },
} as const satisfies Record<PatternPresetId, PatternPreset>;

/** Applies preset defaults and enforces the preset's construction-valid symmetry. */
export function optionsForPreset<Id extends PatternPresetId>(
  presetId: Id,
  options: PatternPresetOptions<Id> = {},
): PatternOptions {
  const preset = PRESETS[presetId];
  const requested = options.symmetry;
  const symmetry = preset.validSymmetries.includes(requested as never)
    ? requested
    : preset.validSymmetries[0];
  return { ...preset.defaults, ...options, symmetry: symmetry as Symmetry };
}
